# Generated by Django 3.1.7 on 2021-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_numberitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.TextField(default='[]', null=True),
        ),
    ]
