# Generated by Django 3.1.7 on 2021-04-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210326_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='unitnumber',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(default='')),
                ('shipping', models.TextField(default='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
