# Generated by Django 3.1.7 on 2021-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210401_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='phonenumber',
            field=models.TextField(default=''),
        ),
    ]
