# Generated by Django 3.1.7 on 2021-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carttotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Purchased', 'Order Purchased'), ('Shipment Received', 'Shipment Received'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Order Placed', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
