# Generated by Django 3.1.7 on 2021-04-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210419_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='carttotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='shippingtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
