# Generated by Django 3.1.7 on 2021-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_btcinvoice_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='btcaddress',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
